### PR TITLE
enable to specify message encoding

### PR DESCRIPTION
**Pull request by mokemokechicken**
If incoming message includes multibyte characters, input_encoding(like 'utf8') option on `update()` method is required.

### CODE REVIEW

**Comment by Sebmaster** [comment]
Hitting the same issue, and the fix seems to work, thanks.

**Comment by jeskew** [comment]
Thanks! Could you add a test?

**Comment by mokemokechicken** [comment]
I added a simple test

**Comment by jeskew** [comment]
Thanks!

**Pull request merged**
